name: CI class

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Pega uma máquina virtual ubuntu para executar a automação dentro dela.

    steps:
    - name: Checkout do código #Clona o código para a máquina virtual
      uses: actions/checkout@v2

    - name: Configurar Node.js # Instalando o gerenciador de dependências
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Intalar dependências
      run: npm install # Instala as dependcias necessárias 

    - name: Executar testes
      run: npm test # Executa os testes
